### PR TITLE
setup broke down; fresh url/name/secret + reimport of data necessary

### PR DESCRIPTION
**Pull request by RubenKelevra**
https://github.com/ipfs/ipfs-cluster/issues/1006

### CODE REVIEW

**Comment by hsanjuan** [comment]
You may want to compact the new archive (which has height of 12000) by running `ipfs-cluster-service state export` to extract the current state, `ipfs-cluster-service state cleanup` and `ipfs-cluster-service state import` to reimport the state in a single dag node, before you announce it to the world.

**Comment by RubenKelevra** [comment]
@hsanjuan it's a fresh import, it just contains that many pins/files. :)

When IPFS-Cluster starts to support sharding I can switch from pinning each file individually to purely recursive pinning.

**Comment by hsanjuan** [comment]
Yes, I am saying that you can reduce 12.000 pins in 12.000 crdt-dag blocks to 12.000 pins in 1 crdt-dag block this way, which makes syncing way faster for anyone joining.

**Comment by RubenKelevra** [comment]
> Yes, I am saying that you can reduce 12.000 pins in 12.000 crdt-dag blocks to 12.000 pins in 1 crdt-dag block this way, which makes syncing way faster for anyone joining.

Alright, took a second time to get what you meant. I'm sorry!

This looks very promising:
```
00:33:59.821  INFO       crdt: crdt Datastore created. Number of heads: 1. Current max-height: 4 crdt.go:262
```

**Review by hsanjuan — APPROVED** [review]

**Comment by hsanjuan** [comment]
My last recommendation would be to set `cluster.pacman.store` to be an `/ipfs` rather than an `/ipns`, and update DNS records when it needs to change (usually not often). IPNS resolution takes a little bit when starting the follower, where fetching a local /ipfs/Qm hash would be instant.

**Pull request merged**
